(define (problem zeno-0) (:domain zeno-travel)
(:customization
(= :time-format "%d/%m/%Y %H:%M:%S")
(= :time-horizon-relative 2500)
(= :time-start "05/06/2007 08:00:00")
(= :time-unit :hours))

(:objects
	p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18 p19 p20 - person
	Almeria Barcelona Bilbao Cadiz Cordoba Gibraltar Granada Huelva Jaen Madrid Malaga Sevilla - city
	a1 a2 a3 a4 a5 a6 a7 a8 a9 - aircraft
)
(:init
	(at p1 Almeria)
	(at p2 Almeria)
	(at p3 Barcelona)
	(at p4 Granada)
	(at p5 Granada)
	(at p6 Granada)
	(at p7 Malaga)
	(at p8 Barcelona)
	(at p9 Madrid)
	(at p10 Malaga)
	(at p11 Malaga)
	(at p12 Almeria)
    (at p13 Granada)
    (at p14 Bilbao)
    (at p15 Bilbao)
    (at p16 Bilbao)
    (at p17 Barcelona)
    (at p18 Huelva)
    (at p19 Madrid)
    (at p20 Madrid)

	(destino p1 Almeria)
    (destino p2 Cadiz)
    (destino p3 Barcelona)
    (destino p4 Gibraltar)
    (destino p5 Gibraltar)
    (destino p6 Cordoba)
    (destino p7 Malaga)
    (destino p8 Madrid)
    (destino p9 Bilbao)
    (destino p10 Jaen)
    (destino p11 Sevilla)
    (destino p12 Almeria)
    (destino p13 Jaen)
    (destino p14 Madrid)
    (destino p15 Madrid)
    (destino p16 Madrid)
    (destino p17 Bilbao)
    (destino p18 Sevilla)
    (destino p19 Bilbao)
    (destino p20 Madrid)

    (= (distance Almeria Almeria) 0)
    (= (distance Almeria Barcelona) 809)
    (= (distance Almeria Bilbao) 958)
    (= (distance Almeria Cadiz) 463)
    (= (distance Almeria Cordoba) 316)
    (= (distance Almeria Gibraltar) 339)
    (= (distance Almeria Granada) 162)
    (= (distance Almeria Huelva) 505)
    (= (distance Almeria Jaen) 220)
    (= (distance Almeria Madrid) 547)
    (= (distance Almeria Malaga) 207)
    (= (distance Almeria Sevilla) 410)

    (= (distance Barcelona Almeria) 809)
    (= (distance Barcelona Barcelona) 0)
    (= (distance Barcelona Bilbao) 620)
    (= (distance Barcelona Cadiz) 1284)
    (= (distance Barcelona Cordoba) 908)
    (= (distance Barcelona Gibraltar) 1124)
    (= (distance Barcelona Granada) 868)
    (= (distance Barcelona Huelva) 1140)
    (= (distance Barcelona Jaen) 804)
    (= (distance Barcelona Madrid) 621)
    (= (distance Barcelona Malaga) 997)
    (= (distance Barcelona Sevilla) 1046)

    (= (distance Bilbao Almeria) 958)
    (= (distance Bilbao Barcelona) 620)
    (= (distance Bilbao Bilbao) 0)
    (= (distance Bilbao Cadiz) 1058)
    (= (distance Bilbao Cordoba) 796)
    (= (distance Bilbao Gibraltar) 1110)
    (= (distance Bilbao Granada) 829)
    (= (distance Bilbao Huelva) 939)
    (= (distance Bilbao Jaen) 730)
    (= (distance Bilbao Madrid) 395)
    (= (distance Bilbao Malaga) 939)
    (= (distance Bilbao Sevilla) 933)

    (= (distance Cadiz Almeria) 463)
    (= (distance Cadiz Barcelona) 1284)
    (= (distance Cadiz Bilbao) 1058)
    (= (distance Cadiz Cadiz) 0)
    (= (distance Cadiz Cordoba) 261)
    (= (distance Cadiz Gibraltar) 124)
    (= (distance Cadiz Granada) 296)
    (= (distance Cadiz Huelva) 214)
    (= (distance Cadiz Jaen) 330)
    (= (distance Cadiz Madrid) 654)
    (= (distance Cadiz Malaga) 240)
    (= (distance Cadiz Sevilla) 126)

    (= (distance Cordoba Almeria) 316)
    (= (distance Cordoba Barcelona) 908)
    (= (distance Cordoba Bilbao) 796)
    (= (distance Cordoba Cadiz) 261)
    (= (distance Cordoba Cordoba) 0)
    (= (distance Cordoba Gibraltar) 294)
    (= (distance Cordoba Granada) 160)
    (= (distance Cordoba Huelva) 241)
    (= (distance Cordoba Jaen) 108)
    (= (distance Cordoba Madrid) 396)
    (= (distance Cordoba Malaga) 165)
    (= (distance Cordoba Sevilla) 143)

    (= (distance Gibraltar Almeria) 339)
    (= (distance Gibraltar Barcelona) 1124)
    (= (distance Gibraltar Bilbao) 1110)
    (= (distance Gibraltar Cadiz) 124)
    (= (distance Gibraltar Cordoba) 294)
    (= (distance Gibraltar Gibraltar) 0)
    (= (distance Gibraltar Granada) 255)
    (= (distance Gibraltar Huelva) 289)
    (= (distance Gibraltar Jaen) 335)
    (= (distance Gibraltar Madrid) 662)
    (= (distance Gibraltar Malaga) 134)
    (= (distance Gibraltar Sevilla) 201)

    (= (distance Granada Almeria) 162)
    (= (distance Granada Barcelona) 868)
    (= (distance Granada Bilbao) 829)
    (= (distance Granada Cadiz) 296)
    (= (distance Granada Cordoba) 160)
    (= (distance Granada Gibraltar) 255)
    (= (distance Granada Granada) 0)
    (= (distance Granada Huelva) 346)
    (= (distance Granada Jaen) 93)
    (= (distance Granada Madrid) 421)
    (= (distance Granada Malaga) 125)
    (= (distance Granada Sevilla) 252)

    (= (distance Huelva Almeria) 505)
    (= (distance Huelva Barcelona) 1140)
    (= (distance Huelva Bilbao) 939)
    (= (distance Huelva Cadiz) 214)
    (= (distance Huelva Cordoba) 241)
    (= (distance Huelva Gibraltar) 289)
    (= (distance Huelva Granada) 346)
    (= (distance Huelva Huelva) 0)
    (= (distance Huelva Jaen) 347)
    (= (distance Huelva Madrid) 591)
    (= (distance Huelva Malaga) 301)
    (= (distance Huelva Sevilla) 95)

    (= (distance Jaen Almeria) 220)
    (= (distance Jaen Barcelona) 804)
    (= (distance Jaen Bilbao) 730)
    (= (distance Jaen Cadiz) 330)
    (= (distance Jaen Cordoba) 108)
    (= (distance Jaen Gibraltar) 335)
    (= (distance Jaen Granada) 93)
    (= (distance Jaen Huelva) 347)
    (= (distance Jaen Jaen) 0)
    (= (distance Jaen Madrid) 335)
    (= (distance Jaen Malaga) 203)
    (= (distance Jaen Sevilla) 246)

    (= (distance Madrid Almeria) 547)
    (= (distance Madrid Barcelona) 621)
    (= (distance Madrid Bilbao) 395)
    (= (distance Madrid Cadiz) 654)
    (= (distance Madrid Cordoba) 396)
    (= (distance Madrid Gibraltar) 662)
    (= (distance Madrid Granada) 421)
    (= (distance Madrid Huelva) 591)
    (= (distance Madrid Jaen) 335)
    (= (distance Madrid Madrid) 0)
    (= (distance Madrid Malaga) 532)
    (= (distance Madrid Sevilla) 534)

    (= (distance Malaga Almeria) 207)
    (= (distance Malaga Barcelona) 997)
    (= (distance Malaga Bilbao) 939)
    (= (distance Malaga Cadiz) 240)
    (= (distance Malaga Cordoba) 165)
    (= (distance Malaga Gibraltar) 134)
    (= (distance Malaga Granada) 125)
    (= (distance Malaga Huelva) 301)
    (= (distance Malaga Jaen) 203)
    (= (distance Malaga Madrid) 532)
    (= (distance Malaga Malaga) 0)
    (= (distance Malaga Sevilla) 209)

    (= (distance Sevilla Almeria) 410)
    (= (distance Sevilla Barcelona) 1046)
    (= (distance Sevilla Bilbao) 933)
    (= (distance Sevilla Cadiz) 126)
    (= (distance Sevilla Cordoba) 143)
    (= (distance Sevilla Gibraltar) 201)
    (= (distance Sevilla Granada) 252)
    (= (distance Sevilla Huelva) 95)
    (= (distance Sevilla Jaen) 246)
    (= (distance Sevilla Madrid) 534)
    (= (distance Sevilla Malaga) 209)
    (= (distance Sevilla Sevilla) 0)

    (at a1 Madrid)
    (= (fuel-limit a1) 5136)
    (= (max-passengers a1) 4)
    (= (passengers a1) 0)
    (= (capacity a1) 5100)
    (= (fuel a1) 400)
    (= (slow-speed a1) 10)
    (= (fast-speed a1) 20)
    (= (slow-burn a1) 1)
    (= (fast-burn a1) 2)    
    (= (refuel-rate a1) 1)
    (= (total-fuel-used a1) 0)
    (= (time-limit a1) 30)

    (at a2 Sevilla)
    (= (fuel-limit a2) 5136)
    (= (max-passengers a2) 2)
    (= (passengers a2) 0)
    (= (capacity a2) 4250)
    (= (fuel a2) 200)
    (= (slow-speed a2) 5)
    (= (fast-speed a2) 15)
    (= (slow-burn a2) 1)
    (= (fast-burn a2) 2)    
    (= (refuel-rate a2) 1)
    (= (total-fuel-used a2) 0)
    (= (time-limit a2) 25)


    (at a3 Malaga)
    (= (fuel-limit a3) 5136)
    (= (max-passengers a3) 7)
    (= (passengers a3) 0)
    (= (capacity a3) 3900)
    (= (fuel a3) 1400)
    (= (slow-speed a3) 20)
    (= (fast-speed a3) 40)
    (= (slow-burn a3) 1)
    (= (fast-burn a3) 2)    
    (= (refuel-rate a3) 1)
    (= (total-fuel-used a3) 0)
    (= (time-limit a3) 20)

    (at a4 Barcelona)
    (= (fuel-limit a4) 5136)
    (= (max-passengers a4) 5)
    (= (passengers a4) 0)
    (= (capacity a4) 5000)
    (= (fuel a4) 100)
    (= (slow-speed a4) 10)
    (= (fast-speed a4) 20)
    (= (slow-burn a4) 1)
    (= (fast-burn a4) 2)    
    (= (refuel-rate a4) 1)
    (= (total-fuel-used a4) 0)
    (= (time-limit a4) 40)

    (at a5 Gibraltar)
    (= (fuel-limit a5) 5136)
    (= (max-passengers a5) 4)
    (= (passengers a5) 0)
    (= (capacity a5) 4600)
    (= (fuel a5) 400)
    (= (slow-speed a5) 11)
    (= (fast-speed a5) 22)
    (= (slow-burn a5) 2)
    (= (fast-burn a5) 3)    
    (= (refuel-rate a5) 1)
    (= (total-fuel-used a5) 0)
    (= (time-limit a5) 19)

    (at a6 Granada)
    (= (fuel-limit a6) 5136)
    (= (max-passengers a6) 3)
    (= (passengers a6) 0)
    (= (capacity a6) 4100)
    (= (fuel a6) 150)
    (= (slow-speed a6) 7)
    (= (fast-speed a6) 14)
    (= (slow-burn a6) 1)
    (= (fast-burn a6) 3)    
    (= (refuel-rate a6) 1)
    (= (total-fuel-used a6) 0)
    (= (time-limit a6) 22)

    (at a7 Granada)
    (= (fuel-limit a7) 5136)
    (= (max-passengers a7) 7)
    (= (passengers a7) 0)
    (= (capacity a7) 4000)
    (= (fuel a7) 150)
    (= (slow-speed a7) 20)
    (= (fast-speed a7) 40)
    (= (slow-burn a7) 1)
    (= (fast-burn a7) 2)    
    (= (refuel-rate a7) 1)
    (= (total-fuel-used a7) 0)
    (= (time-limit a7) 20)

    (at a8 Gibraltar)
    (= (fuel-limit a8) 5136)
    (= (max-passengers a8) 5)
    (= (passengers a8) 0)
    (= (capacity a8) 4500)
    (= (fuel a8) 150)
    (= (slow-speed a8) 10)
    (= (fast-speed a8) 20)
    (= (slow-burn a8) 1)
    (= (fast-burn a8) 3)    
    (= (refuel-rate a8) 1)
    (= (total-fuel-used a8) 0)
    (= (time-limit a8) 24)

    (at a9 Malaga)
    (= (fuel-limit a9) 5136)
    (= (max-passengers a9) 5)
    (= (passengers a9) 0)
    (= (capacity a9) 4500)
    (= (fuel a9) 150)
    (= (slow-speed a9) 10)
    (= (fast-speed a9) 25)
    (= (slow-burn a9) 1)
    (= (fast-burn a9) 2)    
    (= (refuel-rate a9) 1)
    (= (total-fuel-used a9) 0)
    (= (time-limit a9) 30)

    (= (boarding-time) 1)
    (= (debarking-time) 1)
)
(:tasks-goal
	:tasks(
        (transport-person p1 Almeria)
        (transport-person p2 Cadiz)
        (transport-person p3 Barcelona)
        (transport-person p4 Gibraltar)
        (transport-person p5 Gibraltar)
        (transport-person p6 Cordoba)
        (transport-person p7 Malaga)
        (transport-person p8 Madrid)
        (transport-person p9 Bilbao)
        (transport-person p10 Jaen)
        (transport-person p11 Sevilla)
        (transport-person p12 Almeria)
        (transport-person p13 Jaen)
        (transport-person p14 Madrid)
        (transport-person p15 Madrid)
        (transport-person p16 Madrid)
        (transport-person p17 Bilbao)
        (transport-person p18 Sevilla)
        (transport-person p19 Bilbao)
        (transport-person p20 Madrid)
	)
)
)