(define (problem belkan-problem)
	(:domain BELKAN)
	(:objects player1 - Player 
			  z1 z2 z3 z4 z5 z6 z7 z8 z9 z10 z11 z12 - zone 
			  oscar1 - Oscar
			  apple1 - Manzana
			  algorithm1 - Algoritmo
			  gold1 - Oro
			  rose1 - Rosa
			  teacher1 - Profesor
			  prince1 - Principe
			  princess1 - Princesa
			  leo1 - Leonardo
			  witch1 - Bruja
			  shoe1 - Zapatilla
			  bikini1 - Bikini
	)
	(:init
		(connected z1 S z3)
		(connected z3 N z1)
		(connected z3 W z2)
		(connected z2 E z3)
		(connected z2 S z5)
		(connected z5 N z2)
		(connected z5 S z8)
		(connected z8 N z5)
		(connected z8 S z10)
		(connected z10 N z8)
		(connected z5 E z6)
		(connected z6 W z5)
		(connected z5 W z4)
		(connected z4 E z5)
		(connected z4 S z7)
		(connected z7 N z4)
		(connected z10 W z9)
		(connected z9 E z10)
		(connected z10 E z11)
		(connected z11 W z10)
		(connected z11 E z12)
		(connected z12 W z11)
		(terrain z1 Piedra)
		(terrain z2 Agua)
		(terrain z3 Arena)
		(terrain z4 Piedra)
		(terrain z5 Bosque)
		(terrain z5 Piedra)
		(terrain z7 Arena)
		(terrain z8 Piedra)
		(terrain z9 Arena)
		(terrain z10 Arena)
		(terrain z11 Bosque)
		(terrain z12 Arena)
		(oriented player1 S)
		(at player1 z8)
		(at leo1 z1)
		(at prince1 z6)
		(at princess1 z7)
		(at witch1 z9)
		(at teacher1 z12)
		(at apple1 z2)
		(at algorithm1 z3)
		(at gold1 z4)
		(at rose1 z10)
		(at oscar1 z11)
		(at shoe1 z9)
		(is_zapatilla shoe1)
		(at bikini1 z10)
		(is_bikini bikini1)
		(emptyhand player1)
		(emptybag player1)
		(= (traveled player1) 0)
		(= (received teacher1) 0)
		(= (received prince1) 0)
		(= (received princess1) 0)
		(= (received leo1) 0)
		(= (received witch1) 0)
		(= (distance z1 z3) 2)
		(= (distance z3 z1) 2)
		(= (distance z3 z2) 4)
		(= (distance z2 z3) 4)
		(= (distance z2 z5) 3)
		(= (distance z5 z2) 3)
		(= (distance z5 z4) 4)
		(= (distance z4 z5) 4)
		(= (distance z4 z7) 5)
		(= (distance z7 z4) 5)
		(= (distance z5 z6) 5)
		(= (distance z6 z5) 5)
		(= (distance z5 z8) 6)
		(= (distance z8 z5) 6)
		(= (distance z8 z10) 7)
		(= (distance z10 z8) 7)
		(= (distance z10 z9) 6)
		(= (distance z9 z10) 6)
		(= (distance z10 z11) 5)
		(= (distance z11 z10) 5)
		(= (distance z11 z12) 3)
		(= (distance z12 z11) 3)
	)
	(:goal (AND
		(>= (received teacher1) 1)
		(>= (received prince1) 1)
		(>= (received princess1) 1)
		(>= (received witch1) 1)
		(>= (received leo1) 1) )
	)
	(:metric minimize (traveled player1))
)