(define (problem Problema1)
    (:domain Ejercicio6)
    (:objects
        z1 z2 z3 z4 z5 z6 z7 - zone
        bruja1 - Bruja
        princesa1 - Princesa
        player1 player2 - Player
        oscar1 - Oscar
        manzana1 - Manzana
    )
    (:init
        (connected z1 S z3)
        (connected z3 N z1)
        (connected z3 S z6)
        (connected z6 N z3)
        (= (distance z1 z3) 10)
        (= (distance z3 z1) 10)
        (= (distance z3 z6) 5)
        (= (distance z6 z3) 5)
        (terrain z1 Bosque)
        (terrain z3 Arena)
        (terrain z6 Piedra)
        (connected z2 E z3)
        (connected z3 W z2)
        (connected z3 E z4)
        (connected z4 W z3)
        (= (distance z2 z3) 10)
        (= (distance z3 z2) 10)
        (= (distance z3 z4) 5)
        (= (distance z4 z3) 5)
        (terrain z2 Bosque)
        (terrain z3 Arena)
        (terrain z4 Piedra)
        (connected z5 E z6)
        (connected z6 W z5)
        (connected z6 E z7)
        (connected z7 W z6)
        (= (distance z5 z6) 10)
        (= (distance z6 z5) 10)
        (= (distance z6 z7) 5)
        (= (distance z7 z6) 5)
        (terrain z5 Bosque)
        (terrain z6 Bosque)
        (terrain z7 Agua)
        (at bruja1 z1)
        (at manzana1 z4)
        (at oscar1 z5)
        (at player1 z2)
        (at player2 z6)
        (at princesa1 z7)
        (emptyhand player1)
        (oriented player1 S)
        (emptybag player1)
        (= (player-score player1) 0)
        (emptyhand player2)
        (oriented player2 S)
        (emptybag player2)
        (= (player-score player2) 0)
        (= (received princesa1) 0)
        (= (received bruja1) 0)
        (= (score princesa1 oscar1) 5)
        (= (score princesa1 manzana1) 1)
        (= (score bruja1 oscar1) 4)
        (= (score bruja1 manzana1) 10)
        (= (total_score) 0)
        (= (pocket-capacity bruja1) 4)
        (= (pocket-capacity princesa1) 5)
    )
    (:goal
        (AND
            (>= (total_score) 50)
            (>= (player-score player1) 20)
            (>= (player-score player2) 20)
        )
    )
)